from django.db import models
from apps.accounts.models import Organization
import uuid

class DataSource(models.Model):
    """
    Represents a Source of data (e.g., 'Core-Switch-01').
    It belongs to a Tenant (Organization).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='datasources')
    
    name = models.CharField(max_length=255)
    device_type = models.CharField(max_length=100) # e.g. 'network', 'storage', 'vm'
    
    # --- NEW NETWORKING FIELDS FOR AUTOMATION ---
    ip_address = models.GenericIPAddressField(blank=True, null=True, help_text="Required for Ansible SSH/WinRM execution")
    hostname = models.CharField(max_length=255, blank=True, null=True, help_text="FQDN if IP is dynamic or API requires domain")
    
    # This is the "Password" for the Device (API Key) for incoming telemetry
    api_key = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name} ({self.organization.name})"


class DeviceGroup(models.Model):
    """
    Groups multiple DataSources (Devices) together so a single Automation Job
    can target an entire cluster or environment at once.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='device_groups')
    
    name = models.CharField(max_length=255, help_text="e.g., 'All Production Web Servers'")
    description = models.TextField(blank=True, null=True)
    
    # The crucial link: A group contains many devices
    devices = models.ManyToManyField(DataSource, related_name='groups', blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} ({self.organization.name})"



class MetricDefinition(models.Model):
    """
    Maps a raw JSON field to a Dashboard Widget.
    """
    source = models.ForeignKey(DataSource, related_name='metrics', on_delete=models.CASCADE)
    
    # Visual Labels
    label = models.CharField(max_length=100)  # e.g., "CPU Load"
    unit = models.CharField(max_length=50, blank=True) # e.g., "%"
    
    # The Map: Where is the data? e.g., "$.system.stats.cpu"
    json_path = models.CharField(max_length=255)
    
    # The Visual Logic: { "critical": 90, "warning": 75 }
    # threshold_config = models.JSONField(default=dict, blank=True)

    # --- NEW FIELDS FOR THRESHOLDS ---
    threshold_warning = models.FloatField(null=True, blank=True, help_text="Alert if value exceeds this")
    threshold_critical = models.FloatField(null=True, blank=True, help_text="Critical alert if value exceeds this")

    def __str__(self):
        return f"{self.label} for {self.source.name}"

class TelemetryRecord(models.Model):
    """
    The Raw History. We store the full JSON so we can re-analyze it later.
    """
    source = models.ForeignKey(DataSource, related_name='telemetry', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)
    payload = models.JSONField()
    
    class Meta:
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['source', 'timestamp']),
        ]

    def __str__(self):
        return f"Data from {self.source.name} at {self.timestamp}"


class EmailConfiguration(models.Model):
    # 🛡️ THE MULTI-TENANT LOCK
    organization = models.OneToOneField(Organization, on_delete=models.CASCADE, related_name='email_config', null=True, blank=True)
    
    # SMTP Server Settings
    smtp_server = models.CharField(max_length=255, default="smtp.office365.com")
    smtp_port = models.IntegerField(default=587)
    smtp_username = models.CharField(max_length=255, blank=True, null=True)
    smtp_password = models.CharField(max_length=255, blank=True, null=True)
    use_tls = models.BooleanField(default=True)
    
    # Message Routing
    from_address = models.EmailField(default="migdal-alerts@ctcglobal.com")
    recipient_list = models.TextField(help_text="Comma-separated emails", default="admin@ctcglobal.com")
    
    # Template
    subject = models.CharField(max_length=255, default="[Migdal] Automated Infrastructure Report")
    message_body = models.TextField(default="Attached is the latest AI analysis and telemetry report generated by Migdal after the recent Ansible playbook run.")
    
    # Master switch to turn automated emails on/off
    is_active = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Email Configuration"
        verbose_name_plural = "Email Configuration"

    def __str__(self):
        # Update the string representation to show the org name
        if self.organization:
            return f"SMTP Config for {self.organization.name}"
        return "Unassigned SMTP Configuration"

