# Generated by Django 6.0.1 on 2026-03-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='license_expiry',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='max_devices',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='tier',
        ),
    ]
