# Generated by Django 6.0.1 on 2026-02-02 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name e.g. 'Production Gemini'", max_length=100)),
                ('provider_type', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI (GPT)'), ('ollama', 'Ollama (Local)')], max_length=20)),
                ('model_name', models.CharField(default='gemini-1.5-flash', max_length=100)),
                ('api_key', models.CharField(blank=True, help_text='Leave empty for local models', max_length=255)),
                ('api_url', models.CharField(blank=True, help_text='Optional base URL', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.aiprovider')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='core.datasource')),
            ],
        ),
    ]
