# Generated by Django 6.0.1 on 2026-02-04 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ai_engine', '0002_prompttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='report_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='accounts.organization'),
        ),
    ]
