# Generated by Django 6.0.1 on 2026-02-02 01:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=100)),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('json_path', models.CharField(max_length=255)),
                ('threshold_config', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payload', models.JSONField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core.datasource')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['source', 'timestamp'], name='core_teleme_source__eb7c37_idx')],
            },
        ),
    ]
