# Generated by Django 6.0.1 on 2026-02-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricdefinition',
            name='threshold_config',
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='threshold_critical',
            field=models.FloatField(blank=True, help_text='Critical alert if value exceeds this', null=True),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='threshold_warning',
            field=models.FloatField(blank=True, help_text='Alert if value exceeds this', null=True),
        ),
    ]
