# Generated by Django 6.0.1 on 2026-03-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_metricdefinition_threshold_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_server', models.CharField(default='smtp.office365.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('use_tls', models.BooleanField(default=True)),
                ('from_address', models.EmailField(default='migdal-alerts@ctcglobal.com', max_length=254)),
                ('recipient_list', models.TextField(default='admin@ctcglobal.com', help_text='Comma-separated emails')),
                ('subject', models.CharField(default='[Migdal] Automated Infrastructure Report', max_length=255)),
                ('message_body', models.TextField(default='Attached is the latest AI analysis and telemetry report generated by Migdal after the recent Ansible playbook run.')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
    ]
