# Generated by Django 6.0.1 on 2026-03-09 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_organization_license_expiry_and_more'),
        ('core', '0003_emailconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='accounts.organization'),
        ),
    ]
