# Generated by Django 6.0.1 on 2026-03-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailconfiguration_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='hostname',
            field=models.CharField(blank=True, help_text='FQDN if IP is dynamic or API requires domain', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Required for Ansible SSH/WinRM execution', null=True),
        ),
    ]
