# Generated by Django 6.0.1 on 2026-03-18 06:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_organization_license_expiry_and_more'),
        ('core', '0005_datasource_hostname_datasource_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'All Production Web Servers'", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('devices', models.ManyToManyField(blank=True, related_name='groups', to='core.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to='accounts.organization')),
            ],
        ),
    ]
