server {
    listen 80;
    server_name _;

    # 1. Serve the compiled React App
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; 
    }

    # 2. Proxy API requests to Django
    location /api/ {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /admin/ { 
        proxy_pass http://web:8000;
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr;
    }    

    # 3. Serve Django Static Files (Admin panel CSS)
    location /static/ {
        alias /usr/share/nginx/html/static/;

        # alias /app/static/;
    }

    # 4. Serve Uploaded Media
    location /media/ {
        alias /usr/share/nginx/html/media/;

	# alias /app/media/;
    }
}
