from django.db import models
from apps.core.models import DataSource
from apps.accounts.models import Organization

class AIProvider(models.Model):
    """
    Stores configuration for the LLM. 
    Only one provider should be active at a time.
    """

    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='ai_providers', null=True, blank=True)

    PROVIDER_CHOICES = [
        ('gemini', 'Google Gemini'),
        ('openai', 'OpenAI (GPT)'),
        ('ollama', 'Ollama (Local)'),
    ]

    name = models.CharField(max_length=100, help_text="Friendly name e.g. 'Production Gemini'")
    provider_type = models.CharField(max_length=20, choices=PROVIDER_CHOICES)
    
    # The actual technical model name (e.g. 'gemini-1.5-flash' or 'gpt-4o')
    model_name = models.CharField(max_length=100, default='gemini-1.5-flash')
    
    api_key = models.CharField(max_length=255, blank=True, help_text="Leave empty for local models")
    
    # Endpoint URL (Mainly for Ollama or Azure OpenAI)
    api_url = models.CharField(max_length=255, blank=True, null=True, help_text="Optional base URL")

    is_active = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        # Ensure only one provider is active PER ORGANIZATION
        if self.is_active and self.organization:
            AIProvider.objects.filter(
                organization=self.organization, 
                is_active=True
            ).exclude(pk=self.pk).update(is_active=False)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.name} ({self.organization.name if self.organization else 'Global'})"


class PromptTemplate(models.Model):
    """
    Defines the 'Persona' and instructions for the AI.
    e.g. 'Network Analyst' vs 'Security Auditor'
    """

    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, related_name='prompts', null=True, blank=True)

    name = models.CharField(max_length=100) # e.g. "Standard Network Analysis"
    description = models.CharField(max_length=255, blank=True)
    
    # The actual instruction sent to the LLM. 
    # We use {context} as a placeholder for the JSON data.
    template_text = models.TextField(
        help_text="Use {json_data} placeholder where the telemetry should go.",
        default="Analyze the following system telemetry for anomalies:\n\n{json_data}\n\nSummary:"
    )
    
    # If true, this is the default template used if no specific one is requested
    is_default = models.BooleanField(default=False)
    
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        # Ensure only one default PER ORGANIZATION
        if self.is_default and self.organization:
            PromptTemplate.objects.filter(
                organization=self.organization, 
                is_default=True
            ).exclude(pk=self.pk).update(is_default=False)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class AnalysisReport(models.Model):
    """
    The output generated by the AI.
    """
    source = models.ForeignKey(DataSource, related_name='ai_reports', on_delete=models.CASCADE)
    provider = models.ForeignKey(AIProvider, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    # The AI's full response (Markdown format)
    content = models.TextField()
    
    # Was this flagged as an anomaly?
    is_anomaly = models.BooleanField(default=False)

    report_id = models.UUIDField(editable=False, null=True)

    def __str__(self):
        return f"Report for {self.source.name} at {self.created_at}"