# Generated by Django 6.0.1 on 2026-03-10 07:55

import django.db.models.deletion
import django_cryptography.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_organization_license_expiry_and_more'),
        ('core', '0004_emailconfiguration_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Prod vCenter Admin'", max_length=255)),
                ('credential_type', models.CharField(choices=[('machine', 'Machine (SSH/WinRM)'), ('vcenter', 'VMware vCenter'), ('network', 'Network Device (OSPF/BGP)'), ('api', 'Generic API Token')], max_length=50)),
                ('username', models.CharField(blank=True, help_text="e.g., 'root' or 'administrator@vsphere.local'", max_length=255, null=True)),
                ('secret', django_cryptography.fields.encrypt(models.TextField(help_text='Encrypted at rest. Stores the password, API token, or SSH Private Key.'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionEnvironment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'VMware & Dell Storage Ops'", max_length=255)),
                ('collections_json', models.JSONField(default=list, help_text='[{"name": "community.vmware", "version": "3.6.0"}, {"name": "dellemc.powerstore", "version": "2.2.0"}]')),
                ('python_packages_json', models.JSONField(default=list, help_text='["pyvmomi", "requests"]')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Weekly Nginx Patching'", max_length=255)),
                ('cron_schedule', models.CharField(blank=True, help_text="e.g., '0 2 * * 0' for every Sunday at 2 AM", max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_jobs', to='accounts.organization')),
                ('targets', models.ManyToManyField(related_name='targeted_jobs', to='core.datasource')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='automation.credential')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='automation.executionenvironment')),
            ],
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('successful', 'Successful'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automation.automationjob')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Provision New VM'", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('yaml_content', models.TextField(help_text='The raw Ansible YAML payload')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='accounts.organization')),
            ],
        ),
        migrations.AddField(
            model_name='automationjob',
            name='playbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='automation.playbook'),
        ),
    ]
