# Generated by Django 6.0.1 on 2026-03-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('core', '0006_devicegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationjob',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='targeted_jobs', to='core.devicegroup'),
        ),
    ]
