# Generated by Django 6.0.1 on 2026-03-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_automationjob_target_groups'),
        ('core', '0006_devicegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationjob',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='targeted_jobs', to='core.datasource'),
        ),
    ]
